#!/usr/bin/env python3
"""Write notes/copy.md — the words as they now stand, generated.

Never hand-edit notes/copy.md; edit notes/edit-pass.json and re-run:

    python3 build-content.py && python3 build-copy-doc.py
"""
import json, re, pathlib, subprocess

v = json.loads(subprocess.check_output(
    ["node", "-e",
     "eval(require('fs').readFileSync('content.js','utf8'));"
     "process.stdout.write(JSON.stringify({E:ENTRIES.map(e=>e.a),OPENING,HOPE,"
     "QUESTION,PROMISE,CODA,TITLE}))"]).decode())

orig = []
for line in pathlib.Path("notes/why-dams.md").read_text().split("\n"):
    m = re.match(r'^\s*(?:\d+\.|-)\s*(.+?)\s*$', line)
    if m:
        orig.append(m.group(1))

changed = [
 ("02", "I love how he is passionate about the things he cares about"),
 ("03", "How he is consistent with what he wants"),
 ("04", "he Does what he says he will do"),
 ("06", "I love how he cares about his body"),
 ("07", "Listens to what I say"),
 ("08", "Is very helpful"),
 ("13", "I love him, he’s amazing and sweet"),
 ("14", "He’s very patient with me and is not frustrated unless I make him maddd"),
 ("15", "He is just happy to be here - with me"),
 ("16", "I like his music taste"),
 ("17", "he’s crazy about me"),
 ("18", "He wants what’s best for me"),
 ("19", "He only sees me"),
 ("20", "He thinks of me a lot, gave me my first and second jersey"),
 ("21", "He’s very thoughtful"),
 ("22", "He’s empathetic and feels his emotions"),
 ("23", "Pays attention to me"),
]

L = ["# Why dams — the copy",
"",
"*Generated. Do not edit this file by hand — edit `notes/edit-pass.json` and run*",
"*`python3 build-content.py && python3 build-copy-doc.py`.*",
"",
"The original, exactly as first written, is kept at `notes/why-dams.md` and is",
"never modified. Delete `notes/edit-pass.json` and rebuild to get it back.",
"",
"---",
"",
"## Opening",
"",
f"> {v['OPENING']}",
"",
f"{v['HOPE']}",
"",
f"**Question:** {v['QUESTION']}  ",
f"**Promise:** {v['PROMISE']}",
"",
"---",
"",
"## The twenty-four",
""]
for i, t in enumerate(v["E"], 1):
    L.append(f"{i:02d}. {t}")
L += ["",
"---",
"",
"## Coda",
"",
f"> {v['CODA']}",
"",
"---",
"",
"## What was changed, and why",
"",
"**One rule: the note switched between talking *to* him and *about* him.**",
'"I like how **you** take on tasks" sat beside "I love how **he** is passionate."',
"It is a letter addressed to him, so second person is the spine. Every line below",
"changed for that reason and no other — only the pronoun and the verb agreeing",
"with it.",
"",
"*(Numbers in this section are the original note's. The list above renumbers from",
"12 onward, because 12 and 13 were merged.)*",
""]
for n, before in changed:
    L.append(f"- **{n}** ~~{before}~~")
L += ["",
"### Four changes that were not just the pronoun",
"",
"**05** — removed the stray space in `\"How can I help ?\"`.",
"",
"**08** — the author's own rewrite: *You are helpful, always, without being asked",
"and when asked.* The second half is the part people forget to say.",
"",
"**12 and 13 merged.** Both carried \"I love you\". Joined, they keep every phrase",
"from both and free one slot:",
"",
f"> {v['E'][11]}",
"",
"**22 — the author's own rewrite**, which turned a near-repeat of 11 into a",
"different observation. Two fixes to it: `your regulate` to `you regulate`, and a",
"comma before the second clause so the line lands as two things — you feel them,",
"and you handle them.",
"",
"**24 is new**, written later. It is the only line that counts the way the piece",
"counts: one per month, so twenty-four months is twenty-four ice creams. That is",
"why it takes the last slot.",
"",
"### Left alone on purpose",
"",
'"maddd" keeps all three d\'s. "my twin for real" stays. **"Dams sends me money"**',
"is untouched — it is the funniest and most specific line in the note, and polish",
"would kill it.",
"",
"### Still open",
"",
'**09** ends "and helpful", which **08** now owns outright. Trimming it to *You are',
"so incredibly talented* would sharpen both. Not done — that word was put back once",
"already, so it is the author's call.",
""]
pathlib.Path("notes/copy.md").write_text("\n".join(L) + "\n")
print(f"notes/copy.md — {len(v['E'])} lines of copy")
